### ISSUE TITLE
[question]: ignore filters and whitelisting

### ISSUE THREAD

**Issue by nskalis** [cloudflare/cfrpki#29]
Hi,

Is there a possibility to customise/override specific ROAs with mechanisms such as:

* Ignore filters
You can use filters to exclude ROAs matching an ASN and/or prefix

* Whitelist
By adding a whitelist entry you can manually authorise an ASN to originate a prefix in addition to the validated ROAs from the repository.

?

**Comment by lspgn** [comment]
Hi @nskalis,
Unfortunately this is not possible at the moment.
I am thinking of integrating this in GoRTR as it works on the JSON provided rather than OctoRPKI which translates directly the certificates data into a JSON.

Usually overrides can be customized in the router configuration.
Another solution could be a script fetching the JSON produced and filtering it before passing it to GoRTR.

Let me know if that answers your question.

**Comment by lspgn** [comment]
Prepared a branch and an issue:
https://github.com/cloudflare/gortr/issues/34
https://github.com/cloudflare/gortr/tree/feature/filter

**Comment by nskalis** [comment]
thank you, yes, it does.
